(() => {
  "use strict";

  const scriptUrl = new URL(document.currentScript?.src || window.location.href, window.location.href);
  const siteRoot = new URL("./", scriptUrl);
  const assetUrl = (path) => new URL(path, siteRoot).href;
  const freezeList = (items = []) => Object.freeze(items.map((item) => Object.freeze(item)));
  const createAsset = (config) => {
    const sources = [];
    if (config.desktopWebm) sources.push({ src: config.desktopWebm, type: "video/webm" });
    if (config.desktopMp4) sources.push({ src: config.desktopMp4, type: "video/mp4" });
    return Object.freeze({ ...config, sources: freezeList(sources) });
  };

  const badgeDefaults = Object.freeze({
    badge: true,
    badgeAsset: assetUrl("icons/mono-favicon.svg"),
    badgePosition: "bottom-right",
    badgeVariant: "cashmere-squircle",
    badgeSize: "clamp(50px, 7vw, 76px)",
    badgeRight: "calc(9% - (var(--video-badge-size) / 2))",
    badgeBottom: "calc(15.3% - (var(--video-badge-size) / 2))",
    badgeBackground: "#F4ECDD",
    badgeLogoScale: 0.76
  });

  const fireRavioli = createAsset({
    id: "mono-fire-ravioli",
    title: "Fuoco e ravioli",
    chapter: "home",
    primaryPage: "home",
    secondaryUses: freezeList(["home-manifesto", "poster", "short-transition"]),
    originalSourceName: "VIDEO PENTOLA.mp4",
    master: assetUrl("assets/cinematic/source/mono-01-fuoco-ravioli-master.mp4"),
    desktopWebm: assetUrl("assets/cinematic/web/mono-01-fuoco-ravioli-desktop.webm"),
    desktopMp4: assetUrl("assets/cinematic/web/mono-01-fuoco-ravioli-desktop.mp4"),
    mobileMaster: null,
    mobileWebm: null,
    mobileMp4: null,
    posterWebp: assetUrl("assets/cinematic/web/mono-01-fuoco-ravioli-poster.webp"),
    posterAvif: null,
    posterTimestamp: 6.5,
    posterTime: 6.5,
    width: 1280,
    height: 720,
    aspectRatio: "16 / 9",
    duration: 10.005,
    chapterDuration: 20.01,
    fps: 24,
    codec: Object.freeze({ masterVideo: "h264", masterAudio: "aac", desktopWebm: "vp9", desktopMp4: "h264", pixelFormat: "yuv420p" }),
    audio: false,
    masterAudio: true,
    companion: Object.freeze({
      role: "ravioli-cut",
      originalSourceName: "VIDEO AGNOLOTTI.mp4",
      master: assetUrl("assets/cinematic/source/mono-01-ravioli-cut-master.mp4"),
      desktopWebm: assetUrl("assets/cinematic/web/mono-01-ravioli-cut-desktop.webm"),
      desktopMp4: assetUrl("assets/cinematic/web/mono-01-ravioli-cut-desktop.mp4"),
      posterWebp: assetUrl("assets/cinematic/web/mono-01-ravioli-cut-poster.webp"),
      posterTimestamp: 9,
      duration: 10.005
    }),
    playback: "once",
    playbackMode: "once",
    sessionMemory: true,
    sessionKey: "mono-video-seen-fire-ravioli",
    skip: true,
    replay: true,
    visibilityThreshold: 0.4,
    ...badgeDefaults,
    safeTextArea: "left",
    preferredTextSide: "left",
    focalPoint: "58% 54%",
    mobileFocalPoint: "58% 54%",
    objectFit: "cover",
    objectPosition: "58% center",
    mobileStrategy: "contained-landscape",
    preloadStrategy: "poster-high-video-after-critical",
    posterPriority: "high",
    decorative: true,
    status: "approved",
    implementationStatus: "prepared-segmented-home-film",
    notes: "Il capitolo Home e composto da due master originali preservati: pentola/fuoco e taglio ravioli. Nessun upscale o color grading distruttivo."
  });

  const kitchenMagic = createAsset({
    id: "mono-kitchen-magic",
    title: "La cucina lavora",
    chapter: "products",
    primaryPage: "gastronomia",
    secondaryUses: freezeList(["poster", "short-transition", "o-mask"]),
    originalSourceName: "VIDEO CUCINA MAGICA.mp4",
    master: assetUrl("assets/cinematic/source/mono-02-cucina-magica-master.mp4"),
    desktopWebm: assetUrl("assets/cinematic/web/mono-02-cucina-magica-desktop.webm"),
    desktopMp4: assetUrl("assets/cinematic/web/mono-02-cucina-magica-desktop.mp4"),
    mobileMaster: null,
    mobileWebm: null,
    mobileMp4: null,
    posterWebp: assetUrl("assets/cinematic/web/mono-02-cucina-magica-poster.webp"),
    posterAvif: null,
    posterTimestamp: 8.5,
    posterTime: 8.5,
    width: 1280,
    height: 720,
    aspectRatio: "16 / 9",
    duration: 10.005,
    fps: 24,
    codec: Object.freeze({ masterVideo: "h264", masterAudio: "aac", desktopWebm: "vp9", desktopMp4: "h264", pixelFormat: "yuv420p" }),
    audio: false,
    masterAudio: true,
    playback: "loop",
    playbackMode: "once",
    sessionMemory: true,
    sessionKey: "mono-video-seen-kitchen-magic",
    skip: true,
    replay: true,
    visibilityThreshold: 0.35,
    ...badgeDefaults,
    safeTextArea: "outside-video",
    preferredTextSide: "outside-video",
    focalPoint: "52% 58%",
    mobileFocalPoint: "52% 58%",
    objectFit: "cover",
    objectPosition: "center center",
    mobileStrategy: "preserve-landscape",
    preloadStrategy: "poster-first-video-near-viewport",
    posterPriority: "low",
    decorative: true,
    status: "approved",
    implementationStatus: "integrated-runtime-loop-pending-third-brief",
    attribution: "Simbolo a stella incorporato nel master, non alterato; configurazione badge predisposta.",
    notes: "Il terzo brief sostituira il loop runtime con play once, Salta e Rivedi senza cambiare i file preparati."
  });

  const handsTeam = createAsset({
    id: "mono-hands-team",
    title: "Molte mani, una sola squadra",
    chapter: "about",
    primaryPage: "la-bottega",
    secondaryUses: freezeList(["poster", "still", "short-extract", "convivium-mask"]),
    originalSourceName: "VIDEO MANI.mp4",
    master: assetUrl("assets/cinematic/source/mono-03-molte-mani-master.mp4"),
    desktopWebm: assetUrl("assets/cinematic/web/mono-03-molte-mani-desktop.webm"),
    desktopMp4: assetUrl("assets/cinematic/web/mono-03-molte-mani-desktop.mp4"),
    mobileMaster: null,
    mobileWebm: null,
    mobileMp4: null,
    posterWebp: assetUrl("assets/cinematic/web/mono-03-molte-mani-poster.webp"),
    posterAvif: null,
    posterTimestamp: 9,
    posterTime: 9,
    width: 1280,
    height: 720,
    aspectRatio: "16 / 9",
    duration: 10.005,
    fps: 24,
    codec: Object.freeze({ masterVideo: "h264", masterAudio: "aac", desktopWebm: "vp9", desktopMp4: "h264", pixelFormat: "yuv420p" }),
    audio: false,
    masterAudio: true,
    playback: "once",
    playbackMode: "once",
    sessionMemory: true,
    sessionKey: "mono-video-seen-hands-team",
    skip: true,
    replay: true,
    visibilityThreshold: 0.4,
    ...badgeDefaults,
    safeTextArea: "outside-video",
    preferredTextSide: "outside-video",
    focalPoint: "54% 60%",
    mobileFocalPoint: "54% 60%",
    objectFit: "cover",
    objectPosition: "center center",
    mobileStrategy: "preserve-landscape",
    preloadStrategy: "poster-first-video-near-viewport",
    posterPriority: "low",
    decorative: true,
    analyticsMode: "cinematic-controls",
    status: "approved",
    implementationStatus: "integrated",
    attribution: "Simbolo a stella incorporato nel master e coperto nel layout dal badge ufficiale.",
    notes: "Il film integrale resta esclusivo della pagina Chi siamo; Convivium puo usare solo poster, still, maschera o estratto breve."
  });

  const eventTable = createAsset({
    id: "mono-event-table",
    title: "La tavola delle occasioni",
    chapter: "events",
    primaryPage: "eventi",
    secondaryUses: freezeList(["home-closing", "poster", "short-transition"]),
    originalSourceName: null,
    expectedMasterPath: "assets/cinematic/source/mono-04-tavola-eventi-master.mp4",
    master: null,
    desktopWebm: null,
    desktopMp4: null,
    mobileMaster: null,
    mobileWebm: null,
    mobileMp4: null,
    posterWebp: null,
    posterAvif: null,
    posterTimestamp: null,
    posterTime: null,
    width: null,
    height: null,
    aspectRatio: "16 / 9",
    duration: null,
    fps: null,
    codec: null,
    audio: false,
    masterAudio: null,
    playback: "once",
    playbackMode: "once",
    sessionMemory: true,
    sessionKey: "mono-video-seen-event-table",
    skip: true,
    replay: true,
    visibilityThreshold: 0.4,
    ...badgeDefaults,
    safeTextArea: "outside-video",
    preferredTextSide: "outside-video",
    focalPoint: "50% 58%",
    mobileFocalPoint: "50% 58%",
    objectFit: "cover",
    objectPosition: "center center",
    mobileStrategy: "contained-landscape",
    preloadStrategy: "disabled-until-master-arrives",
    posterPriority: "none",
    decorative: true,
    status: "missing-master",
    implementationStatus: "structure-ready-no-fallback-video",
    notes: "Non sostituire con stock o altri film esclusi. Badge e focal point sono provvisori fino all'ispezione del master reale."
  });

  window.MONOCinematicAssets = Object.freeze({
    version: "20260714-cinematic-bible-v1",
    badgeDefaults,
    byId: Object.freeze({
      [fireRavioli.id]: fireRavioli,
      [kitchenMagic.id]: kitchenMagic,
      [handsTeam.id]: handsTeam,
      [eventTable.id]: eventTable
    })
  });
})();
